### PR TITLE
Update hasseb hid library

### PR DESCRIPTION
**Pull request by dgomes**
Previous library was https://github.com/awelkie/pyhidapi which is not even published on pypi

This PR changes to use https://github.com/trezor/cython-hidapi/ which is well supported and comes in several distributions besides https://pypi.org/project/hidapi/

### CODE REVIEW

**Comment by dgomes** [comment]
@rousveiga could you please double check in your setup that everything works ?

**Comment by sde1000** [comment]
Looks good to me.

**Comment by rousveiga** [comment]
@dgomes I do not have access to my setup at the moment, but @cnieves1 may be able to check.

**Comment by dgomes** [comment]
Thank you @sde1000 !

If possible could you make a new release on PyPI ? I depend on it for dali2mqtt 🙈

**Comment by sde1000** [comment]
Done!

**Pull request merged**
