### PR TITLE
Add "level" support to fakes.py

### PR DESCRIPTION
**Pull request by sl-wallace**
This feature branch adds the necessary message handling to fakes.py to
handle the various DALI level control messages, e.g. DAPC,
RecallMaxLevel, etc. Such a feature was found to be helpful when
testing out higher level code which uses this library, by enabling the
use of fake DALI devices which correctly respond to certain messages.

Perhaps this isn’t the ideal place for such code to live, but since
fakes.py already implemented the majority of the necessary features
this seems to be the best fit within the existing structure.

Tests have been added to cover all of the additional code.

### CODE REVIEW

**Comment by sde1000** [comment]
Looks good to me, and will be useful to include.

The only thing blocking me merging it is the use of bare `assert` in the tests — you should be using the various `assertSomething` methods of `unittest.TestCase` instead, eg. `self.assertEqual(resp.value, 0)` instead of `assert resp.value == 0`. See [the unittest documentation](https://docs.python.org/3/library/unittest.html) for details.

**Comment by sl-wallace** [comment]
Thanks for that @sde1000 , I'll update my tests and push some more changes in the next day or two :smile:

**Comment by sl-wallace** [comment]
Hi @sde1000, I've updated the test code to use `assertEqual` rather than bare `assert` statements :smile:

**Comment by sde1000** [comment]
Thank you!

**Pull request merged**
