### PR TITLE
Add driver for Lunatune SCI RS232.

### PR DESCRIPTION
**Pull request by opieters**
I have a Lunatone SCI RS232 device that I would like to add to this project. This is a serial DALI interface, and follows the already existing implementation for the Lunatone LUBA serial driver.

### CODE REVIEW

**Comment by sde1000** [comment]
Thank you.

**Comment by opieters** [comment]
Thank you for merging my PR! When will the next release be available? I'm also working on a DALI integration for home assistant and would like to use this newly added driver to test that implementation.

**Comment by dgomes** [comment]
Might as well through my take on the DALI 2 HA :)

https://github.com/dgomes/dali2mqtt

**Comment by sl-wallace** [comment]
> You're not the only one working on DALI and Home Assistant. I have the [beginnings of an MQTT-based integration](https://github.com/indpubs/dali2hass) and I believe @sl-wallace is working on one too.

@sde1000 unfortunately the company I was working for when making my DALI HA integration has closed down, so I don't have access to the hardware I was using any more. I'll check what will happen to the code I'd written - it worked reasonably well, it would be a shame to have it go to waste. I'd love to be able to release it as open source, I'll see what I can do. Also I kept access to my work GitHub account (obviously, since I'm using it right now), I wanted to remain contactable to support the open source work I'd done - but probably future work would come from my personal account @seanlano. :smile:

**Pull request merged**
