### PR TITLE
Driver overhaul - Add a general contract for writing various drivers for communication

### PR DESCRIPTION
**Pull request by rnixx**
Implements #23.

This PR adds ``dali.driver.base``, which contains general contracts how to implement synchronous and asynchronous DALI drivers and USB backend implementation.

Further it adds a concrete driver implementation for Tridonic DALI USB device. It basically works, but needs more testing and finalization.

### CODE REVIEW

**Comment by rnixx** [comment]
I just found out that I receive 2 frames from DALI USB after DAPC command has been sent.

    2016-05-13 12:02:28,004 - TridonicDALIDriver - INFO - CONSTRUCT
        Direction: USB -> DALI
        Type: TYPE_16BIT
        Ecommand: 0x0
        Address: 0x0
        Command: 0x0
        Status: NONE
        Seqnum: 0x1

    2016-05-13 12:02:28,023 - TridonicDALIDriver - INFO - EXTRACT
        Direction: USB -> DALI
        Type: TYPE_COMPLETE
        Ecommand: 0x0
        Address: 0x0
        Command: 0x0
        Status: 15265
        Seqnum: 0x1

    2016-05-13 12:02:28,034 - TridonicDALIDriver - INFO - EXTRACT
        Direction: USB -> DALI
        Type: TYPE_NO_RESPONSE
        Ecommand: 0x0
        Address: 0x0
        Command: 0x0
        Status: 35328
        Seqnum: 0x1

The first frame received is no response, so should I just dispatch it as regular forward frame in async driver?

Further this requires adoption of the sync driver to read frames until first response occurs.

Any opinions?

**Comment by rnixx** [comment]
Next question arising regards the sequence number. If I receive traffic from DALI bus seqnum is always 0. Thus I need to set seqnum between 1 and 255 in order to get a clue whether received frame refers to my transation?

**Comment by rnixx** [comment]
@sde1000 @caiwan ^

Any feedback on this PR?

**Comment by sde1000** [comment]
I'm afraid I won't have a chance to look at it until after https://www.emfcamp.org/

**Comment by rnixx** [comment]
@sde1000 ok, no worries.

**Comment by rnixx** [comment]
Thank you!

**Pull request merged**
