### PR TITLE
Hasseb driver

### PR DESCRIPTION
**Pull request by hasseb**
New hasseb driver

### CODE REVIEW

**Comment by hasseb** [comment]
I tried to remove the commit messages but didn't succeed. Any instructions for dummies....

**Comment by sde1000** [comment]
Hopefully this series of commands will work for you:
```
# Make sure your master branch is up to date
git checkout master
git pull
# Rename the hasseb_driver branch out of the way
git branch -m hasseb_driver hasseb_driver_old
# Create a new hasseb_driver branch
git checkout -b hasseb_driver
# Merge all the commits from the hasseb_driver_old branch together
git merge --squash hasseb_driver_old
# Commit the merged changes
git commit
# (Edit the commit message, etc.)
# Push the new branch to github; the exact command here will depend on how you have your remotes set up
git push --force github hasseb_driver
```

**Comment by sde1000** [comment]
Not quite: your copy of `master` was not up to date when you did this; it was merge of current-master and changes you made earlier.  At the time of writing, typing `git log` when you're in the master branch needs to show commit 3261d3c7dd52217f6262f7be35d1a0aa456ba8a1 as the first entry.

**Comment by sde1000** [comment]
You may be able to get your `master` branch up to date with the following, assuming you called my repo `sde1000` as before:
```
git checkout master
git fetch sde1000
git reset --hard sde1000/master
```

**Comment by sde1000** [comment]
Looks like that did the job!

**Comment by hasseb** [comment]
Thanks, it seems to work now. I saved the notes for later use :)

**Pull request merged**
