### PR TITLE
Remove superfluous blanklines, absolute imports all over the place, m…

### PR DESCRIPTION
**Pull request by rnixx**
…inor PEP8 issues, use commands module instead of command module in dali.bus

### CODE REVIEW

**Comment by sde1000** [comment]
That's quite a large diff! Did you use a tool, or do it all manually?

docstring style: I use emacs python-mode and it tends to want to put a blank line before the closing `"""` at the end of multi-line docstrings.  Does PEP 8 have anything to say about this?  Is there a way to turn it off?

**Comment by sde1000** [comment]
I think the `__all__` in `dali/__init__.py` is out-of-date; if there's no good reason for it we should remove it, probably just leaving a docstring.

**Comment by sde1000** [comment]
I notice that PEP 257 (referenced from PEP 8) says that single-line docstrings should have the closing `"""` on the same line.

**Comment by rnixx** [comment]
I'm using eclipse with pydev which tells me potential issues, but all changes are done manually.

**Comment by rnixx** [comment]
ok, PEP 257 is not in yet, will have a look

**Comment by sde1000** [comment]
`dali/command.py` - `_check_destination`: first line of docstring should be a summary of the function.  "Destination" should start with lower-case 'd' because it is a parameter name.

**Comment by sde1000** [comment]
Could you separate this into two commits, please (I know it's annoying!) - one with formatting changes only, and the other with bugfixes only (fixing 'command' -> 'commands')?

**Comment by rnixx** [comment]
i do not know anything about emacs python mode, nor do i think PEP 8 prevents you to add a blankline. I'm pretty sure you can turn the blankline check off somehow...

Most (if not all) projects i'm working with have no blanklines at the end of a docstring, so removal on cleanup happens somwhat self-acting ;)

**Comment by rnixx** [comment]
Separating the PR. Really? the code in bus.py never worked as it was and i wonder if there is a real benefit when having two commits?

**Comment by sde1000** [comment]
I can do it if you like - I can pull your commit as-is, fix it up, and make two separate commits myself.

**Comment by rnixx** [comment]
yes please +1

**Comment by sde1000** [comment]
Ok, will do!

**Comment by rnixx** [comment]
thank you

**Comment by sde1000** [comment]
Caught a new bug introduced by reformatting: you changed "r.value != True" to "r.value is True" in bus.py - this is one reason I prefer formatting fixes to be entirely in their own commit, because it's clearly wrong.  If bugfixes and formatting fixes are in the same commit then it's not immediately apparent that this is wrong.

**Comment by rnixx** [comment]
ok, mea culpa, sorry

**Comment by sde1000** [comment]
Ok, I pulled your changes, separated out the bus.py bugfix, fixed the bug introduced by reformatting, and squashed the formatting changes all down to one commit using git rebase --interactive.  I've pushed it to my master branch.

**Pull request closed without merging**
