### PR TITLE
Ability to switch on the DALI PS in Lunatone DALI USB 30mA

### PR DESCRIPTION
**Pull request by markus-becker-tridonic-com**

### CODE REVIEW

**Comment by sde1000** [comment]
Thank you — this looks useful to me. I'm just investigating why the checks are failing on something unrelated, when they succeeded last time.

**Comment by sde1000** [comment]
If you rebase on current master and force-push, the tests should complete successfully this time.

**Comment by markus-becker-tridonic-com** [comment]
@sde1000 rebased.

**Comment by sde1000** [comment]
Merged, thank you.

**Pull request merged**
